version: '3'

services:

  user-behavior:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:5001"
    volumes:
      - ./data:/app/data  # Adjust the paths as necessary
    env_file:
      - .env
    networks:
      - stackcards

  airflow-webserver:
    image: apache/airflow:2.2.0  # You can specify the version you prefer
    environment:
      - AIRFLOW__CORE__EXECUTOR=$AIRFLOW__CORE__EXECUTOR
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=$AIRFLOW__CORE__SQL_ALCHEMY_CONN
      - AIRFLOW__CORE__LOAD_EXAMPLES=$AIRFLOW__CORE__LOAD_EXAMPLES
      - AIRFLOW__CORE__DAGS_FOLDER=$AIRFLOW__CORE__DAGS_FOLDER
    volumes:
      - ./airflow_dags/dags:/usr/local/airflow/dags
      - ./airflow_dags/logs:/usr/local/airflow/logs
    command: webserver
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - stackcards
  
  airflow-scheduler:
    image: apache/airflow:2.2.0
    environment:
      - AIRFLOW__CORE__EXECUTOR=$AIRFLOW__CORE__EXECUTOR
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=$AIRFLOW__CORE__SQL_ALCHEMY_CONN
      - AIRFLOW__CORE__LOAD_EXAMPLES=$AIRFLOW__CORE__LOAD_EXAMPLES
    volumes:
      - ./airflow_dags/dags:/usr/local/airflow/dags
      - ./airflow_dags/logs:/usr/local/airflow/logs
    command: scheduler
    env_file:
      - .env
    networks:
      - stackcards

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    env_file:
      - .env
    networks:
    - stackcards

  fluentd:
    image: fluent/fluentd:v1.14
    container_name: fluentd
    depends_on:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/conf:/fluentd/etc
    environment:
      - "FLUENTD_CONF=fluent.conf"
    env_file:
      - .env
    networks:
    - stackcards

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=$ELASTICSEARCH_URL
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
    env_file:
      - .env
    networks:
      - stackcards

volumes:
  esdata:
    driver: local

networks:
  stackcards:
    driver: bridge
